import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { realpathSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { canonicalJsonV2, sha256Hex } from "../src/canonical-json-v2.ts";
import { BackendApp } from "../src/server.ts";
import type { MesaAdapter } from "../src/mesa-adapter.ts";
import { activationExperimentLineageMatches, evaluateRunAdmission } from "../src/gate3-runtime.ts";

const unavailableMesa: MesaAdapter = {};
const body = async (response: Response): Promise<any> => JSON.parse(await response.text());
const sseEvent = async (reader: ReadableStreamDefaultReader<Uint8Array>, name: string, timeout = 3_000): Promise<any> => { let buffered = ""; const deadline = Date.now() + timeout; while (Date.now() < deadline) { const remaining = deadline - Date.now(); let timer: NodeJS.Timeout | undefined; const read = await Promise.race([reader.read(), new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error(`SSE timeout waiting for ${name}`)), remaining); timer.unref(); })]).finally(() => { if (timer) clearTimeout(timer); }); if (read.done) throw new Error(`SSE closed before ${name}`); buffered += Buffer.from(read.value).toString("utf8"); const blocks = buffered.split("\n\n"); buffered = blocks.pop() ?? ""; for (const block of blocks) { const lines = block.split("\n"); if (lines.find((line) => line === `event: ${name}`)) { const data = lines.find((line) => line.startsWith("data: ")); if (!data) throw new Error("SSE data is missing"); return JSON.parse(data.slice(6)); } } } throw new Error(`SSE timeout waiting for ${name}`); };

test("Gate 3 run admission accepts only the activation experiment root or a same-binding durable descendant", () => {
  const target = { model_revision_id: "model", brief_revision_id: "brief", alignment_revision_id: "alignment", experiment_revision_id: "root" };
  const record = (parent_experiment_revision_id: string | null, overrides: Record<string, unknown> = {}) => ({ model_revision_id: "model", brief_revision_id: "brief", alignment_revision_id: "alignment", parent_experiment_revision_id, ...overrides });
  const valid = new Map<string, unknown>([["root", record(null)], ["child", record("root")], ["grandchild", record("child")]]); const loadValid = (id: string) => { if (!valid.has(id)) throw new Error("missing"); return valid.get(id); };
  assert.equal(activationExperimentLineageMatches("root", target, loadValid), true);
  assert.equal(activationExperimentLineageMatches("child", target, loadValid), true);
  assert.equal(activationExperimentLineageMatches("grandchild", target, loadValid), true);
  assert.equal(activationExperimentLineageMatches("wrong-parent", target, (id) => id === "wrong-parent" ? record("other") : (() => { throw new Error("missing"); })()), false);
  assert.equal(activationExperimentLineageMatches("cross-binding", target, () => record("root", { brief_revision_id: "other" })), false);
  assert.equal(activationExperimentLineageMatches("missing", target, () => { throw new Error("missing"); }), false);
  const cycle = new Map<string, unknown>([["a", record("b")], ["b", record("a")]]); assert.equal(activationExperimentLineageMatches("a", target, (id) => cycle.get(id)), false);
  const current = { decision_brief_revision_id: "brief", alignment_map_revision_id: "alignment", model_revision_id: "model", experiment_revision_id: "root" }; const ready = { status: "ready", run_admission_fenced: false, target }; const evaluate = (activation: unknown, changed = current, load = loadValid) => evaluateRunAdmission(activation, changed, changed.model_revision_id, load);
  assert.deepEqual(evaluate(null), { admissible: false, reason: "activation_missing" });
  assert.deepEqual(evaluate({ ...ready, status: "authorizing", run_admission_fenced: true }), { admissible: false, reason: "activation_not_ready" });
  assert.deepEqual(evaluate({ ...ready, status: "failed_fenced", run_admission_fenced: true }), { admissible: false, reason: "activation_fenced" });
  assert.deepEqual(evaluate({ status: "ready", target }), { admissible: false, reason: "activation_fenced" });
  assert.deepEqual(evaluate({ ...ready, target: null }), { admissible: false, reason: "activation_target_invalid" });
  assert.deepEqual(evaluate(ready, { ...current, model_revision_id: "other" }), { admissible: false, reason: "model_revision_mismatch" });
  assert.deepEqual(evaluate(ready, { ...current, decision_brief_revision_id: "other" }), { admissible: false, reason: "brief_revision_mismatch" });
  assert.deepEqual(evaluate(ready, { ...current, alignment_map_revision_id: "other" }), { admissible: false, reason: "alignment_revision_mismatch" });
  assert.deepEqual(evaluate(ready, { ...current, experiment_revision_id: "missing" }), { admissible: false, reason: "experiment_lineage_invalid" });
  assert.deepEqual(evaluate(ready, { ...current, experiment_revision_id: "wrong-parent" }, (id) => id === "wrong-parent" ? record("other") : (() => { throw new Error("missing"); })()), { admissible: false, reason: "experiment_lineage_invalid" });
  assert.deepEqual(evaluate(ready, { ...current, experiment_revision_id: "cross-binding" }, () => record("root", { alignment_revision_id: "other" })), { admissible: false, reason: "experiment_lineage_invalid" });
  assert.deepEqual(evaluate(ready, { ...current, experiment_revision_id: "a" }, (id) => cycle.get(id)), { admissible: false, reason: "experiment_lineage_invalid" });
  assert.deepEqual(evaluate(ready), { admissible: true, reason: "ready" });
  assert.deepEqual(evaluate(ready, { ...current, experiment_revision_id: "child" }), { admissible: true, reason: "ready" });
  assert.deepEqual(evaluate(ready, { ...current, experiment_revision_id: "grandchild" }), { admissible: true, reason: "ready" });
});

test("Gate 3 default discovery and browser authority are separate, digest-bound projections", async (t) => {
  const workspace = realpathSync(await mkdtemp(join(tmpdir(), "riff-gate3-api-"))); const app = new BackendApp({ mesa: unavailableMesa, workspaceRoot: workspace }); await app.initialize(); const { port } = await app.listen(); const origin = `http://127.0.0.1:${port}`;
  t.after(async () => { await app.close(); await rm(workspace, { recursive: true, force: true }); });
  let response = await fetch(`${origin}/api/projects/default`); assert.equal(response.status, 404); const missing = await body(response); assert.equal(missing.schema_id, "riff://evidence-studio/error/v1"); assert.equal(missing.schema_version, 1); assert.equal(missing.canonical_json_version, "riff-canonical-json-v2"); assert.equal(missing.error.code, "no_default_project");
  response = await fetch(`${origin}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command_id: crypto.randomUUID(), display_name: "Wind evidence", initial_actor: { actor_type: "human", display_name: "Owner", declared_role: "project_owner" } }) }); const created = await body(response); const projectId = created.project.project_id;
  response = await fetch(`${origin}/api/projects/default`); assert.equal(response.status, 200); const discovery = await body(response); assert.equal(discovery.project_id, projectId); assert.equal(discovery.actors.length, 1); assert.deepEqual(Object.keys(discovery.actors[0]).sort(), ["actor_id", "actor_type", "assurance", "declared_role", "display_name"]);
  const durableBefore = await fetch(`${origin}/api/projects/${projectId}/snapshot`).then(body); response = await fetch(`${origin}/api/projects/${projectId}/browser-projection/v1`); assert.equal(response.status, 200); const projection = await body(response); assert.equal(projection.schema_id, "riff://evidence-studio/browser-projection-response/v1"); assert.equal(projection.projection.schema_id, "riff://evidence-studio/project-state/v1"); assert.equal(projection.projection.project_id, projectId); assert.equal(projection.projection.current_records.decision_brief, null); assert.equal(projection.projection.model_activation, null); assert.deepEqual(projection.projection.run_admission, { admissible: false, reason: "activation_missing" }); const unsigned = { ...projection.projection }; delete unsigned.projection_digest; assert.equal(projection.projection_digest, `pd_${sha256Hex(canonicalJsonV2(unsigned))}`); assert.equal(projection.projection.projection_digest, projection.projection_digest);
  const durableAfter = await fetch(`${origin}/api/projects/${projectId}/snapshot`).then(body); assert.deepEqual(durableAfter, durableBefore);
});

test("Gate 3 read routes reject duplicate, unknown, and invalid pagination before evidence access", async (t) => {
  const workspace = realpathSync(await mkdtemp(join(tmpdir(), "riff-gate3-query-"))); const app = new BackendApp({ mesa: unavailableMesa, workspaceRoot: workspace }); await app.initialize(); const { port } = await app.listen(); const origin = `http://127.0.0.1:${port}`;
  t.after(async () => { await app.close(); await rm(workspace, { recursive: true, force: true }); });
  let response = await fetch(`${origin}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command_id: crypto.randomUUID(), display_name: "Wind evidence", initial_actor: { actor_type: "human", display_name: "Owner", declared_role: "project_owner" } }) }); const projectId = (await body(response)).project.project_id; const runId = `run_${"1".repeat(32)}`;
  for (const path of [`/runs/${runId}/kpis?limit=1&limit=1`, `/runs/${runId}/replay?unknown=1`, `/runs/${runId}/event-projection/v1?from_day=2&to_day=1`, `/events/browser-v1?after=0`, `/attestations?unknown=1`]) { response = await fetch(`${origin}/api/projects/${projectId}${path}`); assert.equal(response.status, 422, path); const value = await body(response); assert.equal(value.schema_id, "riff://evidence-studio/error/v1"); assert.equal(value.schema_version, 1); assert.equal(value.canonical_json_version, "riff-canonical-json-v2"); assert.equal(value.error.code, "invalid_request"); }
});

test("Gate 3 default discovery refuses to choose among multiple healthy projects", async (t) => {
  const workspace = realpathSync(await mkdtemp(join(tmpdir(), "riff-gate3-default-"))); const app = new BackendApp({ mesa: unavailableMesa, workspaceRoot: workspace }); await app.initialize(); const { port } = await app.listen(); const origin = `http://127.0.0.1:${port}`;
  t.after(async () => { await app.close(); await rm(workspace, { recursive: true, force: true }); });
  for (const name of ["A", "B"]) await fetch(`${origin}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command_id: crypto.randomUUID(), display_name: name, initial_actor: { actor_type: "human", display_name: "Owner", declared_role: "project_owner" } }) }); const response = await fetch(`${origin}/api/projects/default`); assert.equal(response.status, 409); assert.equal((await body(response)).error.code, "multiple_default_projects");
});

test("Gate 3 browser SSE emits verified snapshot, patch, gap/reload, same-revision reload, and reconnect snapshot", async (t) => {
  const workspace = realpathSync(await mkdtemp(join(tmpdir(), "riff-gate3-sse-"))); const app = new BackendApp({ mesa: unavailableMesa, workspaceRoot: workspace }); await app.initialize(); const { port } = await app.listen(); const origin = `http://127.0.0.1:${port}`;
  t.after(async () => { await app.close(); await rm(workspace, { recursive: true, force: true }); });
  const createResponse = await fetch(`${origin}/api/projects`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command_id: crypto.randomUUID(), display_name: "SSE", initial_actor: { actor_type: "human", display_name: "Owner", declared_role: "project_owner" } }) }); const created = await body(createResponse); const projectId = created.project.project_id; const actorId = created.initial_actor.actor_id; const session = await fetch(`${origin}/api/projects/${projectId}/sessions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ actor_id: actorId }) }).then(body); let revision = 0;
  const stream = await fetch(`${origin}/api/projects/${projectId}/events/browser-v1`, { headers: { accept: "text/event-stream" } }); assert.equal(stream.status, 200); const reader = stream.body!.getReader(); const snapshot = await sseEvent(reader, "browser.project.snapshot.v1"); const unsigned = { ...snapshot.projection }; delete unsigned.projection_digest; assert.equal(snapshot.projection_digest, `pd_${sha256Hex(canonicalJsonV2(unsigned))}`);
  let briefId: string | null = null; const createBrief = async (question: string): Promise<any> => { const response = await fetch(`${origin}/api/projects/${projectId}/brief/revisions`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ command_id: crypto.randomUUID(), project_id: projectId, session_id: session.session_id, base_snapshot_revision: revision, payload: { operation: briefId ? "revise" : "create", parent_decision_brief_revision_id: briefId, question, decision_owner: "Owner", objective: "SSE", constraints: [], assumptions: [], non_goals: [], sources: [] } }) }); const value = await body(response); assert.equal(response.status, 201, JSON.stringify(value)); revision = value.snapshot_revision; briefId = value.decision_brief_revision.decision_brief_revision_id; return value; };
  await createBrief("one"); const patch = await sseEvent(reader, "browser.project.patch.v1"); assert.equal(patch.base_snapshot_revision, 0); assert.equal(patch.snapshot_revision, 1); assert.deepEqual(patch.operations.map((item: any) => [item.op, item.path]), [["replace", ""]]); const patchUnsigned = { ...patch.operations[0].value }; delete patchUnsigned.projection_digest; assert.equal(patch.projection_digest, `pd_${sha256Hex(canonicalJsonV2(patchUnsigned))}`);
  await Promise.all([createBrief("two"), (async () => { while (revision < 2) await new Promise((resolveWait) => setTimeout(resolveWait, 1)); return await createBrief("three"); })()]); const gap = await sseEvent(reader, "browser.project.reload-required.v1"); assert.equal(gap.reason, "revision_gap"); assert.equal(gap.snapshot_revision, 3);
  const original = app.gate3.browserProjection.bind(app.gate3); const current = original(projectId); (app.gate3 as any).browserProjection = () => ({ ...current, projection_digest: `pd_${"f".repeat(64)}` }); const sameRevision = await sseEvent(reader, "browser.project.reload-required.v1"); assert.equal(sameRevision.reason, "projection_changed_while_disconnected"); assert.equal(sameRevision.snapshot_revision, current.snapshot_revision); (app.gate3 as any).browserProjection = original; await reader.cancel();
  const reconnect = await fetch(`${origin}/api/projects/${projectId}/events/browser-v1`, { headers: { accept: "text/event-stream" } }); const reconnectReader = reconnect.body!.getReader(); const reloaded = await sseEvent(reconnectReader, "browser.project.snapshot.v1"); assert.equal(reloaded.snapshot_revision, revision); assert.equal(reloaded.projection_digest, original(projectId).projection_digest); await reconnectReader.cancel();
  const corruptStream = await fetch(`${origin}/api/projects/${projectId}/events/browser-v1`, { headers: { accept: "text/event-stream" } }); const corruptReader = corruptStream.body!.getReader(); await sseEvent(corruptReader, "browser.project.snapshot.v1"); (app.gate3 as any).browserProjection = () => { throw new Error("simulated projection corruption"); }; const closed = await Promise.race([corruptReader.read(), new Promise<never>((_, reject) => { const timer = setTimeout(() => reject(new Error("corrupt SSE did not close")), 2_000); timer.unref(); })]); assert.equal(closed.done, true); (app.gate3 as any).browserProjection = original;
});
