import { expect, test } from "@playwright/test";

const attachOwner = async (page: import("@playwright/test").Page) => { await page.goto("/"); await page.getByLabel(/E2E Owner/).check(); await page.getByRole("button", { name: "Attach selected actor" }).click(); await expect(page.getByRole("main", { name: "Wind-turbine maintenance Evidence Studio" })).toBeVisible(); };
const discardIfStale = async (page: import("@playwright/test").Page) => { const button = page.getByRole("button", { name: "Discard and load current" }); await button.waitFor({ state: "visible", timeout: 2_000 }).catch(() => undefined); if (await button.isVisible().catch(() => false)) await button.click(); };
const policyCard = (page: import("@playwright/test").Page, title: string) => page.locator(".policy-card").filter({ has: page.getByRole("heading", { name: title, level: 4 }) });
const policyValue = (page: import("@playwright/test").Page, title: string, metric: string) => policyCard(page, title).locator("dl div").filter({ hasText: metric }).locator("dd");

test("live backend requires explicit actor attachment and every query keeps the single Evidence surface", async ({ page }) => {
  await page.goto("/");
  await expect(page.getByRole("heading", { name: "Playwright Wind Evidence" })).toBeVisible();
  await expect(page.getByText("No actor is selected silently.")).toBeVisible();
  await page.getByLabel(/E2E Owner/).check();
  await page.getByRole("button", { name: "Attach selected actor" }).click();
  await expect(page.getByRole("main", { name: "Wind-turbine maintenance Evidence Studio" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Brief" })).toHaveAttribute("aria-selected", "true");
  await page.getByRole("tab", { name: "Model" }).click(); await expect(page.locator('[data-testid="model-transition-edge"]')).toHaveCount(16); await expect(page.locator('[data-testid="process-transition"]')).toHaveCount(16);
  await page.getByRole("tab", { name: "Model" }).press("End");
  await expect(page.getByRole("tab", { name: "Evidence" })).toBeFocused();
  await expect(page.getByRole("navigation")).toHaveCount(0);

  const formerModeQuery = `/?${["mo", "de"].join("")}=${["leg", "acy"].join("")}`;
  for (const url of [formerModeQuery, "/?surface=anything"]) {
    await page.goto(url);
    await expect(page.getByRole("heading", { name: "Playwright Wind Evidence" })).toBeVisible();
    await expect(page.getByRole("navigation")).toHaveCount(0);
    await page.getByLabel(/E2E Owner/).check();
    await page.getByRole("button", { name: "Attach selected actor" }).click();
    await expect(page.getByRole("main", { name: "Wind-turbine maintenance Evidence Studio" })).toBeVisible();
  }
});

test("narrow layout exposes an explicit one-pane selector", async ({ page }) => {
  await page.setViewportSize({ width: 820, height: 900 });
  await page.goto("/");
  await page.getByLabel(/E2E Owner/).check();
  await page.getByRole("button", { name: "Attach selected actor" }).click();
  await expect(page.getByRole("button", { name: "Conversation / alignment" })).toBeVisible();
  await page.getByRole("button", { name: "Conversation / alignment" }).click();
  await expect(page.getByRole("complementary", { name: "Alignment and revision context" })).toBeVisible();
});

test("real framed project supports revision, quantitative review, 202 run, restart persistence, verified evidence, and responsive semantics", async ({ page }) => {
  test.setTimeout(150_000); await attachOwner(page);
  await page.getByRole("tab", { name: "Run" }).click(); const runResponse = page.waitForResponse((response) => response.request().method() === "POST" && /\/api\/projects\/[^/]+\/runs$/.test(new URL(response.url()).pathname)); await page.getByRole("button", { name: "Start private draft run" }).click(); expect((await runResponse).status()).toBe(202); await expect(page.getByText(/terminal · succeeded/)).toBeVisible({ timeout: 30_000 }); await discardIfStale(page); await expect(page.locator(".run-card").first().getByText("private_draft", { exact: true })).toBeVisible(); await expect(page.locator(".run-card").first().getByText("draft_unverified", { exact: true })).toBeVisible(); await expect(page.locator(".run-card").first().getByText("workflow_policy_unmet", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Experiment" }).click(); await expect(page.getByRole("heading", { name: "Experiment revision" })).toBeVisible(); await expect(page.locator('[data-testid^="parameter-"]')).toHaveCount(29);
  const crewCount = page.locator('[data-testid="parameter-crew_count"] input'); await crewCount.fill("4"); const revisionBeforeEdit = await page.locator(".revision").textContent(); await page.getByRole("button", { name: "Save as new revision" }).click(); await expect(page.locator(".revision")).not.toHaveText(revisionBeforeEdit ?? ""); await discardIfStale(page);
  await page.getByRole("button", { name: "Reset all" }).click(); await expect(page.getByRole("dialog", { name: "Reset preview" })).toBeVisible(); const revisionBeforeReset = await page.locator(".revision").textContent(); await page.getByRole("button", { name: "Confirm reset as new revision" }).click(); await expect(page.getByRole("dialog", { name: "Reset preview" })).toBeHidden(); await expect(page.locator(".revision")).not.toHaveText(revisionBeforeReset ?? ""); await discardIfStale(page);
  const resetExperimentRevision = await page.getByRole("tabpanel").locator(".identity-row").filter({ hasText:"Revision" }).locator("code").getAttribute("title"); expect(resetExperimentRevision).toMatch(/^er_[0-9a-f]{64}$/);
  await page.getByRole("tab", { name: "Issues & review" }).click(); await expect(page.getByText("No issues. This means no recorded open objection, not proof of correctness.")).toBeVisible(); for (const title of ["Alignment workflow condition", "Experiment workflow condition"]) { await expect(policyValue(page, title, "Human project-owner workflow endorsements")).toHaveText("0"); await expect(policyValue(page, title, "All open issues")).toHaveText("0"); await expect(policyCard(page, title).getByText("Workflow threshold not met", { exact: true })).toBeVisible(); }
  await page.getByLabel("Title").fill("E2E evidence review"); await page.getByLabel("Body").fill("Exercise exact issue and attestation projections."); await page.getByRole("button", { name: "Open issue" }).click(); await page.getByRole("button", { name: "Load authoritative issue detail & history" }).click(); await expect(page.getByText("E2E evidence review", { exact: true })).toBeVisible(); await discardIfStale(page); for (const title of ["Alignment workflow condition", "Experiment workflow condition"]) { await expect(policyValue(page, title, "Open non-blocking issues")).toHaveText("1"); await expect(policyValue(page, title, "All open issues")).toHaveText("1"); }
  await page.getByLabel("Rationale").fill("Reviewed for workflow progression only."); await page.getByRole("button", { name: "Record attestation" }).click(); await expect(page.getByText("Reviewed for workflow progression only.")).toBeVisible(); await expect(page.getByText("effective head").first()).toBeVisible(); await expect(page.getByText("Human attestations: 2 · Agent attestations: 0", { exact: true })).toBeVisible(); await discardIfStale(page); for (const title of ["Alignment workflow condition", "Experiment workflow condition"]) { await expect(policyValue(page, title, "Human project-owner workflow endorsements")).toHaveText("1"); await expect(policyCard(page, title).getByText("Workflow threshold met", { exact: true })).toBeVisible(); }
  await page.getByRole("tab", { name: "Run" }).click(); const editedRunResponse = page.waitForResponse((response) => response.request().method() === "POST" && /\/api\/projects\/[^/]+\/runs$/.test(new URL(response.url()).pathname)); await page.getByRole("button", { name: "Start private draft run" }).click(); expect((await editedRunResponse).status()).toBe(202); await expect(page.getByText(/terminal · succeeded/)).toHaveCount(2, { timeout: 45_000 }); await discardIfStale(page); await expect(page.locator(".run-card").first().locator(".identity-row").filter({ hasText:"Experiment" }).locator("code")).toHaveAttribute("title",resetExperimentRevision!); await expect(page.locator(".run-card").first().getByText("private_draft", { exact: true })).toBeVisible(); await expect(page.locator(".run-card").first().getByText("draft_unverified", { exact: true })).toBeVisible(); await expect(page.locator(".run-card").first().getByText("workflow_policy_met", { exact: true })).toBeVisible(); await page.locator(".run-card").first().getByRole("button", { name: "Select" }).click();
  await expect(page.getByRole("heading", { name: /^Evidence/, level: 2 })).toBeVisible(); await expect(page.getByText("wind-kpi-equal-index-floor-v1").first()).toBeVisible({ timeout: 30_000 }); await expect(page.getByRole("table", { name: /Complete paged daily KPI rows/ })).toBeVisible(); await expect(page.getByRole("table", { name: /Complete paged selected-run event projection/ })).toBeVisible(); await expect(page.getByText(/Loaded \d+\/\d+ exact replay frames/)).toBeVisible(); await expect(page.getByText("Exact daily metrics embedded", { exact: false })).toBeVisible(); const boundary = page.getByRole("complementary", { name: "Evidence claim boundary" }).first(); for (const label of ["Synthetic data", "Single seed", "Behavioral model", "No recommendation", "private_draft", "draft_unverified", "workflow_policy_met", "synthetic_inputs", "single_seed", "no_staffing_recommendation"]) await expect(boundary.getByText(label, { exact: true }).first()).toBeVisible(); const evidenceLinks = page.getByRole("heading", { name:"Exact evidence downloads" }).locator("..").getByRole("link"); await expect(evidenceLinks).toHaveCount(8); const artifactHrefs = await evidenceLinks.evaluateAll((links) => links.map((link) => (link as HTMLAnchorElement).href));
  const restartResponse = await fetch("http://127.0.0.1:8788/restart", { method: "POST" }); expect(restartResponse.status).toBe(200); expect(await restartResponse.json()).toMatchObject({ status: "restarted", generation: 2 });
  await page.reload(); await expect(page.getByText("No actor is selected silently.")).toBeVisible(); await page.getByLabel(/E2E Owner/).check(); await page.getByRole("button", { name: "Attach selected actor" }).click(); await page.getByRole("tab", { name: "Experiment" }).click(); await expect(page.getByRole("tabpanel").locator(".identity-row").filter({ hasText:"Revision" }).locator("code")).toHaveAttribute("title", resetExperimentRevision!); await page.getByRole("tab", { name: "Issues & review" }).click(); await page.getByRole("button", { name: "Load authoritative issue detail & history" }).click(); await expect(page.getByText("E2E evidence review", { exact: true })).toBeVisible(); await expect(page.getByText("Human attestations: 2 · Agent attestations: 0", { exact: true })).toBeVisible(); await page.getByRole("tab", { name: "Evidence" }).click(); await expect(page.getByText("wind-kpi-equal-index-floor-v1").first()).toBeVisible({ timeout: 20_000 }); const persistedLinks = page.getByRole("heading", { name:"Exact evidence downloads" }).locator("..").getByRole("link"); await expect(persistedLinks).toHaveCount(8); expect(await persistedLinks.evaluateAll((links) => links.map((link) => (link as HTMLAnchorElement).href))).toEqual(artifactHrefs);
  await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => { document.documentElement.style.zoom = "2"; }); await expect(page.getByRole("button", { name: "Workbench" })).toBeVisible(); await expect(page.getByRole("tab", { name: "Evidence" })).toHaveAccessibleName("Evidence"); await expect(page.getByRole("table", { name: /Complete paged daily KPI rows/ })).toBeVisible();
});
