import { afterEach, describe, expect, it, vi } from "vitest";
import { HttpEvidenceStudioClient, freezeCommand } from "./api";
import { canonicalJsonV2 } from "./state";
import type { ProjectCommand } from "./types";

const envelope: ProjectCommand<Record<string, unknown>> = { command_id:"7f27db28-84a8-4e62-9a46-0f1b9ad61d5a",project_id:"project_1",session_id:"session_1",base_snapshot_revision:12,payload:{operation:"edit",parent_experiment_revision_id:"er_1",parameter_changes:{crew_count:4},execution_changes:{}} };

describe("frozen command transport", () => {
  afterEach(() => vi.unstubAllGlobals());
  it("freezes canonical bytes plus exact event/result reconciliation contract", async () => { const frozen=await freezeCommand(envelope,"POST","/api/projects/project_1/experiments/revisions","/api/projects/project_1/experiments/revisions"); expect(frozen.canonical_json).toBe(canonicalJsonV2(envelope)); expect(frozen.command_digest).toMatch(/^cmd_[0-9a-f]{64}$/); expect(frozen.command_digest_version).toBe("gate2-command-digest-v1"); expect(frozen.expected_event_type).toBe("experiment.revision_created"); expect(frozen.expected_result_identity).toEqual({}); expect(frozen.observed_result_identity).toBeNull(); expect(Object.isFrozen(frozen)).toBe(true); });
  it("retries response-lost transport with the exact original bytes and command ID", async () => { const bodies:string[]=[]; let calls=0; vi.stubGlobal("fetch",vi.fn(async (_url:string|URL|Request,init?:RequestInit)=>{ calls+=1; bodies.push(String(init?.body)); if(calls===1) throw new TypeError("lost"); return new Response(JSON.stringify({snapshot_revision:13}),{status:201,headers:{"content-type":"application/json"}}); })); const client=new HttpEvidenceStudioClient(); await expect(client.reviseExperiment("project_1",envelope)).rejects.toThrow("lost"); const frozen=client.pendingFrozen()!; expect(frozen.transport_status).toBe("response_lost"); await client.retryFrozen(); expect(bodies).toEqual([frozen.canonical_json,frozen.canonical_json]); expect(JSON.parse(bodies[1]).command_id).toBe(envelope.command_id); });
  it("uses Gate 3 digest v2 and an exact activation terminal-outcome union", async () => { const path="/api/projects/project_1/wind/framed-evidence/activate"; const frozen=await freezeCommand(envelope,"POST",path,path,"gate3-command-digest-v2"); expect(frozen.command_digest_version).toBe("gate3-command-digest-v2"); expect(frozen.command_digest).toMatch(/^cmd_[0-9a-f]{64}$/); expect(frozen.expected_event_type).toBe("model.activation_reconciled"); expect(frozen.expected_terminal_event_types).toEqual(["model.activation_reconciled","model.activation_failed"]); expect(frozen.expected_result_identity).toEqual({activation_id:envelope.command_id}); });
  it("keeps an activation 202 reservation frozen across the HTTP/SSE race", async () => { vi.stubGlobal("fetch",vi.fn(async () => new Response(JSON.stringify({accepted:true,status:"authorizing",snapshot_revision:12}),{status:202,headers:{"content-type":"application/json"}}))); const client=new HttpEvidenceStudioClient(); await client.activate("project_1",envelope); expect(client.pendingFrozen()?.transport_status).toBe("reservation_pending"); const bytes=client.pendingFrozen()?.canonical_json; await client.retryFrozen(); expect(client.pendingFrozen()?.canonical_json).toBe(bytes); expect(client.pendingFrozen()?.transport_status).toBe("reservation_pending"); });
  it("clears a 202 activation after exact-byte retry returns its immutable failed receipt", async () => { const bodies:string[]=[]; let calls=0; const receipt=`acr_${"b".repeat(64)}`; vi.stubGlobal("fetch",vi.fn(async (_url:string|URL|Request,init?:RequestInit)=>{ calls+=1; bodies.push(String(init?.body)); if(calls===1) return new Response(JSON.stringify({accepted:true,status:"authorizing",snapshot_revision:12}),{status:202,headers:{"content-type":"application/json"}}); return new Response(JSON.stringify({schema_id:"riff://evidence-studio/error/v1",schema_version:1,canonical_json_version:"riff-canonical-json-v2",accepted:false,error:{code:"activation_failed_fenced",message:"Activation failed.",correlation_id:"corr",details:{activation_id:envelope.command_id,safe_error_code:"mesa_adapter_failure",snapshot_revision:13,receipt_digest:receipt}}}),{status:409,headers:{"content-type":"application/json"}}); })); const client=new HttpEvidenceStudioClient(); await client.activate("project_1",envelope); const frozen=client.pendingFrozen()!; await expect(client.retryFrozen()).rejects.toMatchObject({code:"activation_failed_fenced",details:{activation_id:envelope.command_id,receipt_digest:receipt}}); expect(bodies).toEqual([frozen.canonical_json,frozen.canonical_json]); expect(client.pendingFrozen()).toBeNull(); });
});
