import { canonicalJsonV2, validateRunReference } from "./state";
import type { AttestationDetailPage, EvidenceIndex, EvidenceStudioClient, EventPage, KpiPage, ModelViewSources, ReplayPage, RunReference, SourceDescriptor, SucceededRunReference } from "./types";

export const DEFAULT_KPI_METRICS = ["availability_fraction", "crew_utilization_fraction", "corrective_queue_length", "planned_queue_length", "operating_count", "working_crew_count", "total_maintenance_cost", "operating_revenue"] as const;
const HEX = /^[0-9a-f]{64}$/;
const SOURCE_KEYS = ["schema_id", "schema_version", "canonical_json_version", "source_kind", "logical_name", "sha256", "identity", "href"];
const SOURCE_IDENTITY_KEYS = ["project_id", "model_revision_id", "brief_revision_id", "alignment_revision_id", "experiment_revision_id", "run_id"];
const KPI_KEYS = ["schema_id", "schema_version", "canonical_json_version", "project_id", "run_id", "experiment_revision_id", "source", "metric_schema_source", "columns", "rows", "after_day", "next_after_day", "has_more"];
const EVENT_KEYS = ["schema_id", "schema_version", "canonical_json_version", "projection_kind", "project_id", "run_id", "experiment_revision_id", "source", "filters", "source_event_count", "after", "scanned_through_sequence", "next_after", "has_more", "events"];
const REPLAY_KEYS = ["schema_id", "schema_version", "canonical_json_version", "page_kind", "project_id", "run_id", "event_source", "manifest_source", "generator_version", "source_set_digest", "sampling_algorithm", "declared_population", "sample_days", "sample_days_sha256", "frame_count", "unavailable_reason", "source_event_ranges", "frames", "after_frame", "next_after_frame", "has_more"];
const ATTESTATION_KEYS = ["schema_id", "schema_version", "canonical_json_version", "project_id", "subject_revision_id", "after", "next_after", "has_more", "items"];
const ATTESTATION_ITEM_KEYS = ["attestation_id", "actor", "subject_revision_ids", "scope", "decision", "rationale", "issue_refs", "created_at", "supersedes_attestation_id", "superseded_by_attestation_id", "effective_head", "record_digest"];
const EVENT_FILTER_KEYS = ["from_day", "to_day", "event_type", "turbine_id", "crew_id", "work_order_id"];
const FRAME_KEYS = ["frame_index", "identity", "day", "phase", "through_event_sequence", "source_event_range_index", "frame_state_sha256", "depot", "turbines", "crews", "queues", "daily_metrics"];
const RANGE_KEYS = ["range_index", "event_count", "first_sequence", "last_sequence", "byte_offset", "byte_length", "raw_range_sha256", "semantic_range_sha256"];
const RUN_IDENTITY_KEYS = ["project_id", "run_id", "model_id", "model_revision_id", "brief_revision_id", "alignment_revision_id", "experiment_revision_id", "preset_id", "seed", "visibility", "trust_label", "workflow_label", "policy_snapshot_digest", "run_admission_digest"];
const EVIDENCE_IDENTITY_KEYS = ["run_id", "model_id", "model_revision_id", "brief_revision_id", "alignment_revision_id", "experiment_revision_id", "preset_id", "seed", "policy_snapshot_digest", "run_admission_digest", "run_intent_digest"];
const ARTIFACT_KEYS = ["artifact_id", "logical_name", "sha256", "href"];
const ARTIFACT_NAMES = ["request.json", "metadata.json", "daily-kpis.csv", "domain-events.jsonl", "summary.json", "replay-manifest.json", "derived-views-manifest.json", "run.log"];
const ARTIFACT_ID = /^artifact_[0-9a-f]{64}$/;
const REPLAY_SUMMARY_KEYS = ["schema_id", "schema_version", "canonical_json_version", "manifest_kind", "manifest_sha256", "generator_version", "sampling_algorithm", "event_source_sha256", "event_semantic_sha256", "event_count", "frame_count", "sample_days_sha256", "claim_labels_sha256", "non_claims_sha256", "unavailable_reason"];
const EVIDENCE_LABEL_KEYS = ["visibility", "trust_label", "workflow_label", "claim_labels", "non_claims"];
const TURBINE_KEYS = ["turbine_id", "x_km", "y_km", "state"];
const CREW_KEYS = ["crew_id", "x_km", "y_km", "state", "turbine_id", "work_order_id"];
const TURBINE_STATES = new Set(["operating", "failed_waiting", "corrective_repair", "planned_maintenance", "major_replacement"]);
const CREW_STATES = new Set(["idle", "driving_to_work", "working", "driving_home"]);
const REQUEST_KEYS = [...RUN_IDENTITY_KEYS, "experiment_sha256", "run_intent_digest", "downstream_request_digest", "experiment_document", "run_admission", "parameters", "horizon_days", "warmup_days", "runtime_profile", "claim_labels"];
const STATE_METRICS: Record<string,string> = { operating:"operating_count", failed_waiting:"failed_waiting_count", corrective_repair:"corrective_repair_count", planned_maintenance:"planned_maintenance_count", major_replacement:"major_replacement_count" };
const CREW_METRICS: Record<string,string> = { idle:"idle_crew_count", driving_to_work:"driving_to_work_crew_count", working:"working_crew_count", driving_home:"driving_home_crew_count" };
const REPLAY_GENERATOR = "wind-worker-sampled-replay-v1";
const REPLAY_SAMPLING = "wind-replay-sample-days-v1";
const EMPTY_ARRAY_SHA256 = "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945";

const plain = (value: unknown): value is Record<string, unknown> => value !== null && typeof value === "object" && !Array.isArray(value);
const exact: (value: unknown, keys: string[], label: string) => asserts value is Record<string, unknown> = (value, keys, label) => { if (!plain(value) || Object.keys(value).sort().join("\n") !== [...keys].sort().join("\n")) throw new Error(`${label} has an unsupported exact keyset.`); };
const schema = (value: Record<string, unknown>, id: string, label: string) => { if (value.schema_id !== id || value.schema_version !== 1 || value.canonical_json_version !== "riff-canonical-json-v2") throw new Error(`${label} has an unsupported schema.`); };
const abort = (signal?: AbortSignal) => { if (signal?.aborted) throw new DOMException("Evidence selection changed.", "AbortError"); };
const hex = async (value: string) => [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(value)))].map((byte) => byte.toString(16).padStart(2, "0")).join("");

const runIdentity = (run: RunReference): Record<string, string | number> => Object.fromEntries(RUN_IDENTITY_KEYS.map((key) => [key, run[key as keyof RunReference] as string | number]));
const validateRunIdentity = (value: Record<string, unknown>, run: RunReference, label: string, exactKeys = false): void => { if (exactKeys) exact(value, RUN_IDENTITY_KEYS, label); for (const [key, expected] of Object.entries(runIdentity(run))) if (value[key] !== expected) throw new Error(`${label} differs from the complete selected-run identity at ${key}.`); };
export type ReplayValidationContext = { parameters: Record<string, unknown>; horizon_days:number; warmup_days:number; runtime_profile:Record<string,unknown>; metric_properties:Record<string,Record<string,unknown>> };
const sampledDays=(horizon:number,warmup:number)=>{ const count=Math.min(120,horizon+1); const days=Array.from({length:count},(_,index)=>Math.floor(index*horizon/(count-1))); if (warmup>0&&warmup<horizon&&!days.includes(warmup)){ let selected=1; for(let index=2;index<days.length-1;index+=1) if(Math.abs(days[index]-warmup)<Math.abs(days[selected]-warmup)||Math.abs(days[index]-warmup)===Math.abs(days[selected]-warmup)&&days[index]<days[selected]) selected=index; days[selected]=warmup; days.sort((a,b)=>a-b); } return [...new Set(days)]; };

async function loadReplayValidationContext(client:EvidenceStudioClient,evidence:EvidenceIndex,kpi:KpiPage|undefined,run:SucceededRunReference,signal?:AbortSignal):Promise<ReplayValidationContext>{
  if(!client.getExactJsonSource) throw new Error("Exact selected-run source loading is unavailable."); const requestSource=evidence.source_links.find((item)=>item.logical_name==="request.json"); if(!requestSource) throw new Error("Selected-run request source is unavailable."); const request=await client.getExactJsonSource(requestSource,signal); abort(signal); exact(request,REQUEST_KEYS,"Selected-run request"); validateRunIdentity(request,run,"Selected-run request");
  if(request.run_intent_digest!==run.run_intent_digest||!/^rq_[0-9a-f]{64}$/.test(String(request.downstream_request_digest))||!plain(request.experiment_document)||!plain(request.parameters)||!plain(request.runtime_profile)||!Number.isSafeInteger(request.horizon_days)||!Number.isSafeInteger(request.warmup_days)||Number(request.horizon_days)<1||Number(request.warmup_days)<0||Number(request.warmup_days)>=Number(request.horizon_days)) throw new Error("Selected-run request context is invalid.");
  const experiment=request.experiment_document; if(experiment.experiment_revision_id!==run.experiment_revision_id||experiment.model_id!==run.model_id||experiment.model_revision_id!==run.model_revision_id||experiment.brief_revision_id!==run.brief_revision_id||experiment.alignment_revision_id!==run.alignment_revision_id||experiment.preset_id!==run.preset_id||!plain(experiment.execution_values)||experiment.execution_values.seed!==run.seed||experiment.execution_values.horizon_days!==request.horizon_days||experiment.execution_values.warmup_days!==request.warmup_days||canonicalJsonV2(experiment.parameters)!==canonicalJsonV2(request.parameters)||canonicalJsonV2(experiment.runtime_profile)!==canonicalJsonV2(request.runtime_profile)) throw new Error("Selected experiment differs from the selected run request.");
  const experimentBytes=`${canonicalJsonV2(experiment)}${experiment.schema_id==="riff://evidence-studio/experiment-revision/framed/v1"?"\n":""}`; if(request.experiment_sha256!==await hex(experimentBytes)) throw new Error("Selected experiment source digest is invalid.");
  const width=request.parameters.farm_width_km,height=request.parameters.farm_height_km,turbines=request.parameters.turbine_count,crews=request.parameters.crew_count; if(typeof width!=="number"||!Number.isFinite(width)||width<=0||typeof height!=="number"||!Number.isFinite(height)||height<=0||!Number.isSafeInteger(turbines)||Number(turbines)<1||!Number.isSafeInteger(crews)||Number(crews)<1) throw new Error("Selected experiment replay bounds are invalid.");
  let properties:Record<string,Record<string,unknown>>={}; if(kpi){ if(kpi.metric_schema_source.logical_name!=="metric-schema.json"||kpi.metric_schema_source.source_kind!=="model_bundle"||kpi.metric_schema_source.identity.project_id!==run.project_id||kpi.metric_schema_source.identity.model_revision_id!==run.model_revision_id||kpi.metric_schema_source.identity.brief_revision_id!==null||kpi.metric_schema_source.identity.alignment_revision_id!==null||kpi.metric_schema_source.identity.experiment_revision_id!==null||kpi.metric_schema_source.identity.run_id!==null) throw new Error("Selected-run metric schema source identity is invalid."); const metricSchema=await client.getExactJsonSource(kpi.metric_schema_source,signal); abort(signal); if(!plain(metricSchema.properties)) throw new Error("Selected-run metric schema is invalid."); properties=metricSchema.properties as Record<string,Record<string,unknown>>; for(const declaration of Object.values(properties)) if(!plain(declaration)||!["integer","number","boolean"].includes(String(declaration.type))) throw new Error("Selected-run metric declaration is invalid."); }
  return {parameters:request.parameters,horizon_days:Number(request.horizon_days),warmup_days:Number(request.warmup_days),runtime_profile:request.runtime_profile,metric_properties:properties};
}

export function validateSourceDescriptor(value: SourceDescriptor, expected: { projectId: string; run?: RunReference; modelRevisionId?: string | null }, label: string): void {
  exact(value, SOURCE_KEYS, label); exact(value.identity, SOURCE_IDENTITY_KEYS, `${label} identity`); schema(value, "riff://evidence-studio/source-descriptor/v1", label);
  if (!HEX.test(value.sha256) || value.identity.project_id !== expected.projectId || expected.run && Object.entries({ project_id: expected.run.project_id, run_id: expected.run.run_id, model_revision_id: expected.run.model_revision_id, brief_revision_id: expected.run.brief_revision_id, alignment_revision_id: expected.run.alignment_revision_id, experiment_revision_id: expected.run.experiment_revision_id }).some(([key, item]) => value.identity[key as keyof SourceDescriptor["identity"]] !== item) || expected.modelRevisionId !== undefined && value.identity.model_revision_id !== expected.modelRevisionId || !value.href.startsWith(`/api/projects/${encodeURIComponent(expected.projectId)}/`)) throw new Error(`${label} identity is invalid.`);
}

export function verifyModelViewSources(value: ModelViewSources, projectId: string, modelRevisionId: string, expectedDigest: string): ModelViewSources {
  exact(value, ["schema_id", "schema_version", "canonical_json_version", "project_id", "model_id", "model_revision_id", "generator_contract_version", "sources", "contract_bindings", "model_spec", "parameter_schema", "execution_field_schema", "metric_schema", "visualization", "traceability", "source_set_digest"], "Model view source response");
  schema(value, "riff://evidence-studio/model-view-sources/v1", "Model view source response");
  exact(value.sources, ["model_spec", "parameter_schema", "execution_field_schema", "metric_schema", "visualization", "traceability"], "Model view source map"); exact(value.contract_bindings, ["default_preset", "provenance"], "Model contract bindings");
  if (value.project_id !== projectId || value.model_id !== "wind-turbine-maintenance" || value.model_revision_id !== modelRevisionId || value.generator_contract_version !== "wind-evidence-view-contract-v1" || value.source_set_digest !== expectedDigest) throw new Error("Model view source identity mismatch.");
  for (const descriptor of [...Object.values(value.sources), ...Object.values(value.contract_bindings)]) validateSourceDescriptor(descriptor, { projectId, modelRevisionId }, `Model source ${descriptor.logical_name}`);
  return value;
}

export async function downsampleKpis(rows: Array<Record<string, string | number>>, metricKeys: string[], warmupDays: number, sourceSha256: string) {
  if (!rows.length || metricKeys.length < 1 || metricKeys.length > 8 || new Set(metricKeys).size !== metricKeys.length || !HEX.test(sourceSha256)) throw new Error("KPI sampling inputs are invalid.");
  const keys = [...metricKeys].sort(); const warmup = rows.findIndex((row) => row.sim_time_days === warmupDays); if (warmup < 0) throw new Error("The exact warm-up KPI row is missing.");
  for (let index = 0; index < rows.length; index += 1) { const day = Number(rows[index].sim_time_days); if (!Number.isFinite(day) || index > 0 && day <= Number(rows[index - 1].sim_time_days)) throw new Error("KPI source days are not finite and strictly increasing."); }
  const valuesByKey = new Map(keys.map((key) => { if (!(key in rows[0])) throw new Error(`KPI metric ${key} is undeclared.`); const values = rows.map((row) => Number(row[key])); if (values.some((value) => !Number.isFinite(value))) throw new Error(`KPI metric ${key} is not finite.`); return [key, values] as const; }));
  let indexes: number[];
  if (rows.length <= 300) indexes = Array.from({ length: rows.length }, (_, index) => index);
  else { const mandatory = new Set([0, rows.length - 1, warmup]); for (const key of keys) { const values = valuesByKey.get(key)!; let min = 0, max = 0; for (let index = 1; index < rows.length; index += 1) { if (values[index] < values[min]) min = index; if (values[index] > values[max]) max = index; } mandatory.add(min); mandatory.add(max); } const budget = 300 - mandatory.size; for (let j = 1; j <= budget; j += 1) mandatory.add(Math.floor(j * (rows.length - 1) / (budget + 1))); indexes = [...mandatory].sort((a, b) => a - b); }
  if (indexes.length > 300 || !indexes.includes(warmup)) throw new Error("KPI sampling violated its point or warm-up bound.");
  const preimage = { algorithm_version: "wind-kpi-equal-index-floor-v1", source_sha256: sourceSha256, metric_keys: keys, warmup_days: warmupDays, source_indexes: indexes };
  return { downsampling_algorithm: preimage.algorithm_version, source_row_count: rows.length, source_indexes: indexes, rows: indexes.map((index) => rows[index]), downsampling_digest: await hex(canonicalJsonV2(preimage)) };
}

export function validateKpiPage(page: KpiPage, projectId: string, run: RunReference, after: number): void {
  exact(page, KPI_KEYS, "KPI page"); schema(page, "riff://evidence-studio/kpi-page/v1", "KPI page"); validateSourceDescriptor(page.source, { projectId, run }, "KPI source"); validateSourceDescriptor(page.metric_schema_source, { projectId, modelRevisionId: run.model_revision_id }, "KPI metric schema source");
  if (page.project_id !== projectId || page.run_id !== run.run_id || page.experiment_revision_id !== run.experiment_revision_id || page.after_day !== after || page.next_after_day < after || !Array.isArray(page.columns) || !Array.isArray(page.rows)) throw new Error("KPI page identity or cursor is invalid.");
  const keys = page.columns.map((column) => column.key); if (new Set(keys).size !== keys.length) throw new Error("KPI columns are duplicated.");
  for (const row of page.rows) { if (!plain(row) || Object.keys(row).sort().join("\n") !== [...keys].sort().join("\n")) throw new Error("KPI row schema or identity is invalid."); validateRunIdentity(row, run, "KPI row"); }
  if (page.rows.some((row, index) => index > 0 && Number(row.sim_time_days) <= Number(page.rows[index - 1].sim_time_days)) || page.rows.length && Number(page.rows[0].sim_time_days) <= after || page.rows.length && Number(page.rows.at(-1)!.sim_time_days) !== page.next_after_day || page.has_more && page.next_after_day <= after) throw new Error("KPI page range does not strictly advance.");
}

const requestedEventFilters = (filters: Record<string, string>) => ({ from_day: filters.from_day ? Number(filters.from_day) : null, to_day: filters.to_day ? Number(filters.to_day) : null, event_type: filters.event_type || null, turbine_id: filters.turbine_id || null, crew_id: filters.crew_id || null, work_order_id: filters.work_order_id || null });

export function validateEventPage(page: EventPage, projectId: string, run: RunReference, filters: Record<string, string>, after: number): void {
  exact(page, EVENT_KEYS, "Event page"); schema(page, "riff://evidence-studio/filtered-domain-event-projection-page/v1", "Event page"); exact(page.filters, EVENT_FILTER_KEYS, "Event filters"); validateSourceDescriptor(page.source, { projectId, run }, "Event source");
  if (page.projection_kind !== "filtered_domain_events" || page.project_id !== projectId || page.run_id !== run.run_id || page.experiment_revision_id !== run.experiment_revision_id || !Array.isArray(page.events) || !Number.isSafeInteger(page.source_event_count) || page.source_event_count < 0 || !Number.isSafeInteger(page.after) || page.after !== after || !Number.isSafeInteger(page.scanned_through_sequence) || page.scanned_through_sequence !== page.next_after || page.next_after < after || page.next_after > page.source_event_count || page.has_more !== (page.next_after < page.source_event_count)) throw new Error("Event page identity or cursor is invalid.");
  if (canonicalJsonV2(page.filters) !== canonicalJsonV2(requestedEventFilters(filters))) throw new Error("Event page filters differ from the active exact request.");
  for (let index = 0; index < page.events.length; index += 1) { const event = page.events[index]; exact(event, [...RUN_IDENTITY_KEYS, "event_id", "sequence", "sim_time_days", "event_type", "phase", "turbine_id", "crew_id", "work_order_id", "correlation_id", "before_state", "after_state", "payload"], "Domain event"); validateRunIdentity(event, run, "Domain event"); if (!Number.isSafeInteger(event.sequence) || event.sequence <= after || event.sequence > page.scanned_through_sequence || index > 0 && event.sequence <= page.events[index - 1].sequence || !Number.isFinite(event.sim_time_days) || !Number.isSafeInteger(event.phase) || !plain(event.payload)) throw new Error("Domain event identity or range is invalid."); }
}

export function validateReplayPage(page: ReplayPage, projectId: string, run: RunReference, after: number, evidence?: EvidenceIndex, context?:ReplayValidationContext): void {
  exact(page, REPLAY_KEYS, "Replay page"); schema(page, "riff://evidence-studio/replay-page/v1", "Replay page"); validateSourceDescriptor(page.event_source, { projectId, run }, "Replay event source"); validateSourceDescriptor(page.manifest_source, { projectId, run }, "Replay manifest source");
  exact(page.declared_population, ["turbine_count", "crew_count"], "Replay declared population");
  if (page.project_id !== projectId || page.run_id !== run.run_id || page.event_source.logical_name !== "domain-events.jsonl" || page.manifest_source.logical_name !== "replay-manifest.json" || !/^replay_[0-9a-f]{64}$/.test(page.source_set_digest) || !Array.isArray(page.frames) || !Array.isArray(page.source_event_ranges) || !Array.isArray(page.sample_days) || page.sample_days.some((day,index)=>!Number.isSafeInteger(day) || day < 0 || index > 0 && day <= page.sample_days[index-1]) || !Number.isSafeInteger(page.frame_count) || page.frame_count < 0 || page.sample_days.length !== page.frame_count || !Number.isSafeInteger(page.declared_population.turbine_count) || !Number.isSafeInteger(page.declared_population.crew_count) || !Number.isSafeInteger(page.after_frame) || page.after_frame !== after || !Number.isSafeInteger(page.next_after_frame) || page.next_after_frame < after || page.next_after_frame >= page.frame_count && page.frame_count > 0 || page.has_more !== (page.next_after_frame < page.frame_count - 1)) throw new Error("Replay page identity or cursor is invalid.");
  switch (page.page_kind) {
    case "complete": if (!context || page.generator_version !== REPLAY_GENERATOR || page.sampling_algorithm !== REPLAY_SAMPLING || !HEX.test(String(page.sample_days_sha256)) || page.unavailable_reason !== null || page.frame_count < 1 || page.frame_count > 120 || page.declared_population.turbine_count < 1 || page.declared_population.turbine_count > 100 || page.declared_population.crew_count < 1 || page.declared_population.crew_count > 50 || page.declared_population.turbine_count!==context.parameters.turbine_count || page.declared_population.crew_count!==context.parameters.crew_count || canonicalJsonV2(page.sample_days)!==canonicalJsonV2(sampledDays(context.horizon_days,context.warmup_days))) throw new Error("Complete replay discriminator is invalid."); break;
    case "unavailable_population_limit": if (!context || page.generator_version !== REPLAY_GENERATOR || page.sampling_algorithm !== REPLAY_SAMPLING || page.sample_days_sha256 !== EMPTY_ARRAY_SHA256 || page.unavailable_reason !== "population_exceeds_frame_contract" || page.frame_count !== 0 || page.sample_days.length || page.frames.length || page.source_event_ranges.length || page.declared_population.turbine_count < 1 || page.declared_population.crew_count < 1 || page.declared_population.turbine_count <= 100 && page.declared_population.crew_count <= 50 || page.declared_population.turbine_count!==context.parameters.turbine_count || page.declared_population.crew_count!==context.parameters.crew_count) throw new Error("Unavailable replay discriminator is invalid."); break;
    case "legacy_frameless": if (page.generator_version !== null || page.sampling_algorithm !== null || page.sample_days_sha256 !== null || page.unavailable_reason !== "legacy_frameless_manifest" || page.frame_count !== 0 || page.sample_days.length || page.frames.length || page.source_event_ranges.length || page.declared_population.turbine_count !== 0 || page.declared_population.crew_count !== 0) throw new Error("Legacy replay discriminator is invalid."); break;
    default: throw new Error("Replay page discriminator is invalid.");
  }
  if (evidence) { const eventArtifact=evidence.artifacts.find((item)=>item.logical_name==="domain-events.jsonl"); const manifestArtifact=evidence.artifacts.find((item)=>item.logical_name==="replay-manifest.json"); if (!eventArtifact || !manifestArtifact || page.event_source.sha256 !== eventArtifact.sha256 || page.event_source.href !== eventArtifact.href || page.manifest_source.sha256 !== manifestArtifact.sha256 || page.manifest_source.href !== manifestArtifact.href) throw new Error("Replay page source provenance is invalid."); }
  if (page.source_event_ranges.length !== page.frames.length) throw new Error("Replay frame/source ranges are not one-to-one.");
  for (let index = 0; index < page.frames.length; index += 1) {
    const frame = page.frames[index]; const range = page.source_event_ranges[index]; const expectedIndex = after + index + 1;
    exact(range, RANGE_KEYS, "Replay source range"); exact(frame, FRAME_KEYS, "Replay frame"); exact(frame.depot, ["x_km", "y_km"], "Replay depot"); exact(frame.queues, ["corrective", "planned"], "Replay queues"); validateRunIdentity(frame.identity, run, "Replay frame identity", true);
    const previous = page.source_event_ranges[index - 1];
    if (frame.frame_index !== expectedIndex || frame.source_event_range_index !== expectedIndex || frame.frame_index >= page.frame_count || frame.day !== page.sample_days[frame.frame_index] || !context || frame.phase !== (frame.day===context.horizon_days?"horizon_end":frame.day<context.warmup_days?"warmup":"measurement") || !/^fs_[0-9a-f]{64}$/.test(frame.frame_state_sha256) || !Array.isArray(frame.turbines) || !Array.isArray(frame.crews) || frame.turbines.length !== page.declared_population.turbine_count || frame.crews.length !== page.declared_population.crew_count || !Number.isSafeInteger(frame.queues.corrective) || frame.queues.corrective < 0 || !Number.isSafeInteger(frame.queues.planned) || frame.queues.planned < 0 || range.range_index !== expectedIndex || !Number.isSafeInteger(range.event_count) || range.event_count < 1 || !Number.isSafeInteger(range.first_sequence) || !Number.isSafeInteger(range.last_sequence) || range.last_sequence - range.first_sequence + 1 !== range.event_count || !Number.isSafeInteger(range.byte_offset) || range.byte_offset < 0 || !Number.isSafeInteger(range.byte_length) || range.byte_length < 1 || frame.through_event_sequence !== range.last_sequence || !HEX.test(range.raw_range_sha256) || !HEX.test(range.semantic_range_sha256) || index === 0 && after === -1 && (range.first_sequence !== 1 || range.byte_offset !== 0) || previous && (range.first_sequence !== previous.last_sequence + 1 || range.byte_offset !== previous.byte_offset + previous.byte_length)) throw new Error("Replay frame/source range identity or continuity is invalid.");
    exact(frame.daily_metrics,Object.keys(context.metric_properties),"Replay daily metrics"); for(const [name,declaration] of Object.entries(context.metric_properties)){ const value=frame.daily_metrics[name]; if(declaration.type==="boolean"?typeof value!=="boolean":typeof value!=="number"||!Number.isFinite(value)||declaration.type==="integer"&&!Number.isInteger(value)) throw new Error("Replay daily metric is invalid."); }
    const turbineIds:string[]=[]; for (const item of frame.turbines) { exact(item,TURBINE_KEYS,"Replay turbine"); if (!/^turbine-[0-9]{4}$/.test(item.turbine_id) || typeof item.x_km !== "number" || !Number.isFinite(item.x_km) || item.x_km < 0 || item.x_km>Number(context.parameters.farm_width_km) || typeof item.y_km !== "number" || !Number.isFinite(item.y_km) || item.y_km < 0 || item.y_km>Number(context.parameters.farm_height_km) || !TURBINE_STATES.has(item.state)) throw new Error("Replay turbine entity is invalid."); turbineIds.push(item.turbine_id); }
    const crewIds:string[]=[]; for (const item of frame.crews) { exact(item,CREW_KEYS,"Replay crew"); if (!/^crew-[0-9]{3}$/.test(item.crew_id) || typeof item.x_km !== "number" || !Number.isFinite(item.x_km) || item.x_km < 0 || item.x_km>Number(context.parameters.farm_width_km) || typeof item.y_km !== "number" || !Number.isFinite(item.y_km) || item.y_km < 0 || item.y_km>Number(context.parameters.farm_height_km) || !CREW_STATES.has(item.state) || item.turbine_id !== null && !/^turbine-[0-9]{4}$/.test(item.turbine_id) || item.work_order_id !== null && !/^work-[0-9]{8}$/.test(item.work_order_id)) throw new Error("Replay crew entity is invalid."); crewIds.push(item.crew_id); }
    if (turbineIds.join("\n") !== [...new Set(turbineIds)].sort().join("\n") || crewIds.join("\n") !== [...new Set(crewIds)].sort().join("\n")) throw new Error("Replay entity IDs are not sorted unique.");
    if(frame.queues.corrective!==frame.daily_metrics.corrective_queue_length||frame.queues.planned!==frame.daily_metrics.planned_queue_length||Object.entries(STATE_METRICS).some(([state,metric])=>frame.turbines.filter((item)=>item.state===state).length!==frame.daily_metrics[metric])||Object.entries(CREW_METRICS).some(([state,metric])=>frame.crews.filter((item)=>item.state===state).length!==frame.daily_metrics[metric])) throw new Error("Replay frame aggregates differ from daily metrics.");
  }
  if (page.next_after_frame !== (page.frames.at(-1)?.frame_index ?? after)) throw new Error("Replay page range does not exactly match its cursor.");
}

export function validateEvidenceIndex(evidence: EvidenceIndex, projectId: string, selectedRun: SucceededRunReference): void {
  const fail = (message: string): never => { throw new Error(`Run evidence identity mismatch: ${message}`); };
  exact(evidence, ["schema_id", "schema_version", "canonical_json_version", "project_id", "run", "identity", "labels", "summary", "replay_manifest_summary", "derived_views_manifest", "artifacts", "source_links"], "Run evidence index"); schema(evidence, "riff://evidence-studio/run-evidence-index/v1", "Run evidence index");
  const expected = validateRunReference(selectedRun, projectId); const indexed = validateRunReference(evidence.run, projectId);
  if (expected.reference_kind !== "terminal" || expected.status !== "succeeded") fail("selected run");
  if (indexed.reference_kind !== "terminal" || indexed.status !== "succeeded" || canonicalJsonV2(indexed) !== canonicalJsonV2(expected)) fail("evidence run");
  const succeeded = indexed as SucceededRunReference;
  if (evidence.project_id !== projectId || !Array.isArray(evidence.artifacts) || evidence.artifacts.length !== ARTIFACT_NAMES.length) fail("evidence index");
  const ids: string[] = [];
  for (let index = 0; index < evidence.artifacts.length; index += 1) { const artifact = evidence.artifacts[index]; exact(artifact, ARTIFACT_KEYS, "Evidence artifact"); if (artifact.logical_name !== ARTIFACT_NAMES[index] || !ARTIFACT_ID.test(artifact.artifact_id) || !HEX.test(artifact.sha256) || artifact.href !== `/api/projects/${encodeURIComponent(projectId)}/artifacts/${encodeURIComponent(artifact.artifact_id)}`) fail(`artifact ${index}`); ids.push(artifact.artifact_id); }
  if (new Set(ids).size !== ARTIFACT_NAMES.length || canonicalJsonV2([...ids].sort()) !== canonicalJsonV2(succeeded.artifact_ids)) fail("artifact IDs");
  if (!Array.isArray(evidence.source_links) || evidence.source_links.length !== ARTIFACT_NAMES.length) fail("source links");
  for (let index = 0; index < evidence.source_links.length; index += 1) { const descriptor=evidence.source_links[index]; const artifact=evidence.artifacts[index]; validateSourceDescriptor(descriptor,{projectId,run:succeeded},`Evidence source ${index}`); if (descriptor.source_kind !== "run_artifact" || descriptor.logical_name !== ARTIFACT_NAMES[index] || descriptor.sha256 !== artifact.sha256 || descriptor.href !== artifact.href) fail(`source link ${index}`); }
  const summary=evidence.replay_manifest_summary; exact(summary,REPLAY_SUMMARY_KEYS,"Replay manifest summary"); schema(summary,"riff://evidence-studio/replay-manifest-summary/v1","Replay manifest summary");
  exact(evidence.labels,EVIDENCE_LABEL_KEYS,"Evidence labels"); if (!Array.isArray(evidence.labels.claim_labels) || !Array.isArray(evidence.labels.non_claims) || evidence.labels.claim_labels.some((item)=>typeof item!=="string") || evidence.labels.non_claims.some((item)=>typeof item!=="string")) fail("evidence labels");
  if (!["complete","unavailable_population_limit","legacy_frameless"].includes(String(summary.manifest_kind)) || !HEX.test(String(summary.manifest_sha256)) || !HEX.test(String(summary.event_source_sha256)) || !HEX.test(String(summary.event_semantic_sha256)) || !Number.isSafeInteger(summary.event_count) || Number(summary.event_count) < 1 || !Number.isSafeInteger(summary.frame_count) || Number(summary.frame_count) < 0 || !HEX.test(String(summary.claim_labels_sha256))) fail("replay summary");
  if (summary.manifest_kind === "complete" && (summary.generator_version !== REPLAY_GENERATOR || summary.sampling_algorithm !== REPLAY_SAMPLING || !HEX.test(String(summary.sample_days_sha256)) || summary.unavailable_reason !== null || summary.non_claims_sha256 === null || !HEX.test(String(summary.non_claims_sha256)) || Number(summary.frame_count) < 1 || Number(summary.frame_count) > 120) || summary.manifest_kind === "unavailable_population_limit" && (summary.generator_version !== REPLAY_GENERATOR || summary.sampling_algorithm !== REPLAY_SAMPLING || summary.sample_days_sha256 !== EMPTY_ARRAY_SHA256 || summary.unavailable_reason !== "population_exceeds_frame_contract" || summary.non_claims_sha256 === null || !HEX.test(String(summary.non_claims_sha256)) || summary.frame_count !== 0) || summary.manifest_kind === "legacy_frameless" && (summary.generator_version !== null || summary.sampling_algorithm !== null || summary.sample_days_sha256 !== null || summary.unavailable_reason !== "legacy_frameless_manifest" || summary.non_claims_sha256 !== null || summary.frame_count !== 0)) fail("replay summary discriminator");
  exact(evidence.identity, EVIDENCE_IDENTITY_KEYS, "Evidence identity"); for (const key of EVIDENCE_IDENTITY_KEYS) if (evidence.identity[key] !== succeeded[key as keyof RunReference]) fail(`evidence identity ${key}`);
  if (evidence.labels.visibility !== succeeded.visibility || evidence.labels.trust_label !== succeeded.trust_label || evidence.labels.workflow_label !== succeeded.workflow_label) fail("run labels");
  for (const descriptor of evidence.source_links) validateSourceDescriptor(descriptor, { projectId, run: succeeded }, `Evidence source ${descriptor.logical_name}`);
}

export function verifyRunPageIdentities(projectId: string, run: RunReference, evidence: EvidenceIndex, kpi: KpiPage, events: EventPage, replay: ReplayPage): void {
  const fail = (message: string): never => { throw new Error(`Run evidence identity mismatch: ${message}`); };
  validateEvidenceIndex(evidence, projectId, run as SucceededRunReference);
  if (kpi.project_id !== projectId || kpi.run_id !== run.run_id || kpi.experiment_revision_id !== run.experiment_revision_id || events.project_id !== projectId || events.run_id !== run.run_id || replay.project_id !== projectId || replay.run_id !== run.run_id) fail("page tuple");
  const summary=evidence.replay_manifest_summary; const eventArtifact=evidence.artifacts.find((item)=>item.logical_name==="domain-events.jsonl"); const manifestArtifact=evidence.artifacts.find((item)=>item.logical_name==="replay-manifest.json");
  if (summary.manifest_kind !== replay.page_kind || summary.manifest_sha256 !== replay.manifest_source.sha256 || summary.generator_version !== replay.generator_version || summary.sampling_algorithm !== replay.sampling_algorithm || summary.event_source_sha256 !== replay.event_source.sha256 || summary.event_count !== events.source_event_count || summary.frame_count !== replay.frame_count || summary.sample_days_sha256 !== replay.sample_days_sha256 || summary.unavailable_reason !== replay.unavailable_reason || !eventArtifact || !manifestArtifact || replay.event_source.sha256 !== eventArtifact.sha256 || replay.event_source.href !== eventArtifact.href || replay.manifest_source.sha256 !== manifestArtifact.sha256 || replay.manifest_source.href !== manifestArtifact.href) fail("replay provenance");
}

export async function loadCompleteRunPages(client: EvidenceStudioClient, projectId: string, run: SucceededRunReference, filters: Record<string, string>, signal?: AbortSignal) {
  abort(signal); const evidence = await client.getEvidence(projectId, run.run_id, signal); abort(signal); validateEvidenceIndex(evidence, projectId, run);
  const replaySummary=evidence.replay_manifest_summary; const claimDigest=await hex(canonicalJsonV2(evidence.labels.claim_labels)); const nonClaimDigest=await hex(canonicalJsonV2(evidence.labels.non_claims)); if (replaySummary.claim_labels_sha256 !== claimDigest || (replaySummary.manifest_kind === "legacy_frameless" ? replaySummary.non_claims_sha256 !== null : replaySummary.non_claims_sha256 !== nonClaimDigest)) throw new Error("Replay label provenance digest is invalid.");
  const kpiPages: KpiPage[] = []; let afterDay = -1; for (let guard = 0; guard < 10_000; guard += 1) { abort(signal); const page = await client.getKpis(projectId, run.run_id, afterDay, signal); validateKpiPage(page, projectId, run, afterDay); kpiPages.push(page); if (!page.has_more) break; afterDay = page.next_after_day; } if (!kpiPages.length || kpiPages.at(-1)!.has_more) throw new Error("KPI pagination did not terminate completely.");
  let replayContext=await loadReplayValidationContext(client,evidence,undefined,run,signal);
  const eventPages: EventPage[] = []; let after = 0; for (let guard = 0; guard < 100_000; guard += 1) { abort(signal); const page = await client.getEvents(projectId, run.run_id, filters, after, signal); validateEventPage(page, projectId, run, filters, after); eventPages.push(page); if (!page.has_more) break; after = page.next_after; } if (!eventPages.length || eventPages.at(-1)!.has_more) throw new Error("Event pagination did not terminate completely.");
  const replayPages: ReplayPage[] = []; let afterFrame = -1; for (let guard = 0; guard < 1_000; guard += 1) { abort(signal); const page = await client.getReplay(projectId, run.run_id, afterFrame, signal); if(!replayPages.length&&page.page_kind==="complete") replayContext=await loadReplayValidationContext(client,evidence,kpiPages[0],run,signal); validateReplayPage(page, projectId, run, afterFrame,evidence,replayContext); if (page.page_kind !== "legacy_frameless" && page.sample_days_sha256 !== await hex(canonicalJsonV2(page.sample_days))) throw new Error("Replay sample-days digest is invalid."); for(const frame of page.frames){ const preimage={schema_id:"riff://wind-turbine-maintenance/replay-frame-state/v1",schema_version:1,canonical_json_version:"riff-canonical-json-v2",model_id:run.model_id,model_revision_id:run.model_revision_id,experiment_revision_id:run.experiment_revision_id,preset_id:run.preset_id,seed:run.seed,day:frame.day,phase:frame.phase,depot:frame.depot,turbines:frame.turbines,crews:frame.crews,queues:frame.queues,daily_metrics:frame.daily_metrics}; if(frame.frame_state_sha256!==`fs_${await hex(canonicalJsonV2(preimage))}`) throw new Error("Replay frame-state digest is invalid."); } const pageSourceSet=`replay_${await hex(canonicalJsonV2({event:page.event_source.sha256,manifest:page.manifest_source.sha256}))}`; if (page.source_set_digest !== pageSourceSet) throw new Error("Replay source-set provenance is invalid."); replayPages.push(page); if (!page.has_more) break; afterFrame = page.next_after_frame; } if (!replayPages.length || replayPages.at(-1)!.has_more) throw new Error("Replay pagination did not terminate completely.");
  abort(signal); if (kpiPages.some((page) => page.source.sha256 !== kpiPages[0].source.sha256 || page.metric_schema_source.sha256 !== kpiPages[0].metric_schema_source.sha256 || canonicalJsonV2(page.columns) !== canonicalJsonV2(kpiPages[0].columns)) || eventPages.some((page) => page.source.sha256 !== eventPages[0].source.sha256 || canonicalJsonV2(page.filters) !== canonicalJsonV2(eventPages[0].filters) || page.source_event_count !== eventPages[0].source_event_count) || replayPages.some((page) => canonicalJsonV2(page.event_source) !== canonicalJsonV2(replayPages[0].event_source) || canonicalJsonV2(page.manifest_source) !== canonicalJsonV2(replayPages[0].manifest_source) || page.source_set_digest !== replayPages[0].source_set_digest || page.page_kind !== replayPages[0].page_kind || page.generator_version !== replayPages[0].generator_version || page.sampling_algorithm !== replayPages[0].sampling_algorithm || page.sample_days_sha256 !== replayPages[0].sample_days_sha256 || page.unavailable_reason !== replayPages[0].unavailable_reason || page.frame_count !== replayPages[0].frame_count || canonicalJsonV2(page.declared_population) !== canonicalJsonV2(replayPages[0].declared_population) || canonicalJsonV2(page.sample_days) !== canonicalJsonV2(replayPages[0].sample_days))) throw new Error("Run evidence source identity changed across pages.");
  const expectedReplaySourceSet=`replay_${await hex(canonicalJsonV2({event:replayPages[0].event_source.sha256,manifest:replayPages[0].manifest_source.sha256}))}`; if (replayPages[0].source_set_digest !== expectedReplaySourceSet) throw new Error("Replay source-set provenance is invalid.");
  if (eventPages.at(-1)!.scanned_through_sequence !== eventPages[0].source_event_count) throw new Error("Event pagination did not prove complete source scanning.");
  const allFrames = replayPages.flatMap((page) => page.frames); const allRanges = replayPages.flatMap((page) => page.source_event_ranges); const frameCount = replayPages[0].frame_count;
  if (allFrames.length !== frameCount || allRanges.length !== frameCount || allFrames.some((frame, index) => frame.frame_index !== index || frame.source_event_range_index !== index || allRanges[index].range_index !== index || index > 0 && (allRanges[index].first_sequence !== allRanges[index - 1].last_sequence + 1 || allRanges[index].byte_offset !== allRanges[index - 1].byte_offset + allRanges[index - 1].byte_length))) throw new Error("Replay pagination did not prove complete contiguous frames and ranges.");
  if (replayPages[0].page_kind === "complete" ? !allRanges.length || allRanges[0].first_sequence !== 1 || allRanges.at(-1)!.last_sequence !== replaySummary.event_count || replaySummary.event_count !== eventPages[0].source_event_count : allFrames.length !== 0 || allRanges.length !== 0) throw new Error("Replay ranges do not exactly cover the declared event source.");
  const kpis: KpiPage = { ...kpiPages[0], rows: kpiPages.flatMap((page) => page.rows), has_more: false, next_after_day: kpiPages.at(-1)!.next_after_day, page_ranges: kpiPages.map((page, index) => ({ page: index + 1, request_after: page.after_day, first: page.rows.length ? Number(page.rows[0].sim_time_days) : null, last: page.rows.length ? Number(page.rows.at(-1)!.sim_time_days) : null, count: page.rows.length })) };
  const events: EventPage = { ...eventPages[0], events: eventPages.flatMap((page) => page.events), has_more: false, next_after: eventPages.at(-1)!.next_after, scanned_through_sequence: eventPages.at(-1)!.scanned_through_sequence, page_ranges: eventPages.map((page, index) => ({ page: index + 1, request_after: page.after, first: page.events[0]?.sequence ?? null, last: page.events.at(-1)?.sequence ?? null, count: page.events.length })) };
  const replay: ReplayPage = { ...replayPages[0], frames: allFrames, source_event_ranges: allRanges, has_more: false, next_after_frame: replayPages.at(-1)!.next_after_frame, page_ranges: replayPages.map((page, index) => ({ page: index + 1, request_after: page.after_frame, first: page.frames[0]?.frame_index ?? null, last: page.frames.at(-1)?.frame_index ?? null, count: page.frames.length })) };
  verifyRunPageIdentities(projectId, run, evidence, kpis, events, replay); return { evidence, kpis, events, replay, replayContext };
}

function validateAttestationPage(page: AttestationDetailPage, projectId: string, subjectId: string, after: string | null): void {
  exact(page, ATTESTATION_KEYS, "Attestation page"); schema(page, "riff://evidence-studio/attestation-detail-page/v1", "Attestation page"); if (page.project_id !== projectId || page.subject_revision_id !== subjectId || page.after !== after) throw new Error("Attestation page identity/cursor mismatch.");
  for (const item of page.items) { exact(item, ATTESTATION_ITEM_KEYS, "Attestation detail"); exact(item.actor, ["actor_id", "display_name", "actor_type", "declared_role", "assurance"], "Attestation actor"); if (!item.subject_revision_ids.includes(subjectId) || !Number.isFinite(Date.parse(item.created_at)) || typeof item.effective_head !== "boolean" || !item.record_digest) throw new Error("Attestation detail identity is invalid."); for (const ref of item.issue_refs) exact(ref, ["issue_id", "title", "status", "href"], "Attestation issue reference"); }
  if (page.has_more && (!page.next_after || page.next_after === after) || !page.has_more && page.next_after !== null) throw new Error("Attestation cursor continuity is invalid.");
}

export async function loadAllAttestations(client: EvidenceStudioClient, projectId: string, subjectId: string, signal?: AbortSignal): Promise<AttestationDetailPage> {
  const pages: AttestationDetailPage[] = []; let after: string | null = null;
  for (let guard = 0; guard < 100_000; guard += 1) { abort(signal); const page = await client.getAttestations(projectId, subjectId, after, signal); abort(signal); validateAttestationPage(page, projectId, subjectId, after); pages.push(page); if (!page.has_more) break; after = page.next_after; }
  if (!pages.length || pages.at(-1)!.has_more) throw new Error("Attestation pagination did not terminate completely.");
  return { ...pages[0], items: pages.flatMap((page) => page.items), has_more: false, next_after: null };
}
