import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { ModelDiagram, ParameterField, ProcessSwimlane } from "./EvidenceStudioApp";
import type { ExecutionFieldSchema, ModelViewSources, ParameterSchema } from "./types";

const asset = (name: string) => JSON.parse(readFileSync(resolve(process.cwd(), "../mesa_service/src/mesa_service/model_assets/wind_turbine_maintenance_framed", name), "utf8"));

describe("real framed schemas render without inferred metadata", () => {
  it("renders parameter display name, unit, range and provenance", () => { const schema=asset("parameter-schema.json") as ParameterSchema; const property=schema.properties.crew_count; render(<ParameterField fieldKey="crew_count" property={property} current={3} defaultValue={3} value={3} disabled={false} onChange={vi.fn()}/>); expect(screen.getByLabelText("Crew Count")).toHaveAttribute("type","number"); expect(screen.getByText(/count · 1…50/)).toBeInTheDocument(); expect(screen.getByText(/synthetic-demo-assumption/)).toBeInTheDocument(); });
  it("renders the real execution schema although it has no section or display fields", () => { const schema=asset("execution-field-schema.json") as ExecutionFieldSchema; const property=schema.properties.horizon_days; expect("section_id" in property).toBe(false); render(<ParameterField fieldKey="horizon_days" property={property} current={1095} defaultValue={1095} value={1095} disabled={false} onChange={vi.fn()}/>); expect(screen.getByLabelText("horizon_days")).toHaveAttribute("min","1"); expect(screen.getByLabelText("horizon_days")).toHaveAttribute("max","3660"); });
  it("renders every source transition as a labelled graph edge and a dynamic unsliced lane item", () => { const descriptor=(logical_name:string)=>({schema_id:"riff://evidence-studio/source-descriptor/v1",schema_version:1,canonical_json_version:"riff-canonical-json-v2",source_kind:"model_bundle",logical_name,sha256:"a".repeat(64),identity:{project_id:"project",model_revision_id:"model",brief_revision_id:null,alignment_revision_id:null,experiment_revision_id:null,run_id:null},href:`/api/projects/project/${logical_name}`}); const transitions=Array.from({length:7},(_,index)=>({event_type:`event_${index}`,entity:"turbine",from_state:index%2?"failed":"operating",to_state:index%2?"operating":"failed",lane:"dynamic-lane"})); const sources={model_id:"wind-turbine-maintenance",model_revision_id:"model",generator_contract_version:"wind-evidence-view-contract-v1",source_set_digest:"views",model_spec:{entities:{turbine:{states:["operating","failed"],initial_state:"operating"}},transition_events:transitions},visualization:{process_swimlane_view:{lanes:["declared-empty-lane"]}},sources:{model_spec:descriptor("model-spec.json"),visualization:descriptor("visualization.json")}} as unknown as ModelViewSources; const graph=render(<ModelDiagram sources={sources}/>); expect(graph.container.querySelectorAll('[data-testid="model-transition-edge"]')).toHaveLength(7); expect(screen.getByRole("img",{name:/event-labelled transition edges/})).toBeInTheDocument(); graph.unmount(); const lanes=render(<ProcessSwimlane sources={sources}/>); expect(lanes.container.querySelectorAll('[data-testid="process-transition"]')).toHaveLength(7); expect(lanes.container.querySelector('[data-testid="process-lane-declared-empty-lane"]')).toBeInTheDocument(); expect(lanes.container.querySelector('[data-testid="process-lane-dynamic-lane"]')).toBeInTheDocument(); });
});
